#!/usr/bin/env python3
"""Small, local-first toolkit for the repository's LLM-maintained wiki.

The LLM does the interpretation and the synthesis. This module performs only
deterministic bookkeeping: it registers immutable sources, scaffolds a page,
rebuilds the content index, searches markdown, records operations, and checks
wiki health.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import unicodedata
from dataclasses import dataclass
from datetime import date
from pathlib import Path

DEFAULT_WIKI_ROOT = Path(__file__).resolve().parents[1] / "wiki"
PAGE_ROOT = "pages"
REQUIRED_METADATA = ("type", "title", "created", "updated", "sources")
INDEX_MARKER = "<!-- This file is generated by scripts/wiki.py index. -->"
LINK_PATTERN = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")


class WikiError(Exception):
    """An expected user-facing wiki operation error."""


@dataclass(frozen=True)
class SearchResult:
    path: Path
    score: int
    snippet: str


def slugify(value: str) -> str:
    """Return a stable, filesystem-safe slug for a page or source."""

    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", normalized.lower()).strip("-")
    return slug or "untitled"


def _parse_scalar(value: str) -> str | list[str]:
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            raise WikiError(f"invalid frontmatter list: {value}") from exc
        if not isinstance(parsed, list):
            raise WikiError(f"frontmatter list expected: {value}")
        return parsed
    if len(value) >= 2 and value[0] == value[-1] == '"':
        try:
            unquoted = json.loads(value)
        except json.JSONDecodeError as exc:
            raise WikiError(f"invalid frontmatter string: {value}") from exc
        if not isinstance(unquoted, str):
            raise WikiError(f"frontmatter string expected: {value}")
        return unquoted
    return value


def parse_frontmatter(text: str) -> tuple[dict[str, object], str]:
    """Parse the small YAML subset that wiki pages use."""

    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        raise WikiError("frontmatter starts with '---' but has no closing '---'")

    metadata: dict[str, object] = {}
    block = text[4:end]
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise WikiError(f"invalid frontmatter line: {line}")
        key, value = line.split(":", 1)
        metadata[key.strip()] = _parse_scalar(value)
    body = text[end + len("\n---") :].lstrip("\n")
    return metadata, body


def _yaml_value(value: object) -> str:
    if isinstance(value, list):
        return json.dumps(value, ensure_ascii=False)
    return json.dumps(str(value), ensure_ascii=False)


def render_frontmatter(metadata: dict[str, object]) -> str:
    lines = ["---"]
    for key, value in metadata.items():
        lines.append(f"{key}: {_yaml_value(value)}")
    lines.extend(["---", ""])
    return "\n".join(lines)


def _first_paragraph(body: str) -> str:
    paragraphs = re.split(r"\n\s*\n", body.strip())
    for paragraph in paragraphs:
        clean = re.sub(r"^#+\s+", "", paragraph.strip())
        clean = re.sub(r"\[[^]]+\]\(([^)]+)\)", r"\1", clean)
        if clean and not clean.startswith("-") and not clean.startswith(">"):
            return re.sub(r"\s+", " ", clean)[:220]
    return "No summary yet."


def _display_type(page_type: str) -> str:
    return {
        "source": "Sources",
        "concept": "Concepts",
        "architecture": "Architecture",
        "decision": "Decisions",
        "answer": "Filed answers",
        "overview": "Overview",
    }.get(page_type, page_type.replace("-", " ").title())


class Wiki:
    """Operations rooted at one wiki directory."""

    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    @property
    def index_path(self) -> Path:
        return self.root / "index.md"

    @property
    def log_path(self) -> Path:
        return self.root / "log.md"

    @property
    def page_root(self) -> Path:
        return self.root / PAGE_ROOT

    def init(self) -> None:
        for directory in (
            self.root / "raw",
            self.page_root / "sources",
            self.page_root / "concepts",
            self.page_root / "architecture",
            self.page_root / "decisions",
            self.page_root / "answers",
        ):
            directory.mkdir(parents=True, exist_ok=True)

        if not (self.root / "README.md").exists():
            (self.root / "README.md").write_text(
                "# LLM Wiki\n\nSee [AGENTS.md](AGENTS.md) and [SCHEMA.md](SCHEMA.md).\n",
                encoding="utf-8",
            )
        if not (self.root / "raw" / "README.md").exists():
            (self.root / "raw" / "README.md").write_text(
                "# Raw sources\n\n"
                "Files in this directory are immutable inputs. "
                "Add sources with `make wiki-ingest SOURCE=...`.\n",
                encoding="utf-8",
            )
        if not self.log_path.exists():
            self.log_path.write_text(
                "# Wiki log\n\nAppend-only record of ingests, queries, and lint passes.\n\n",
                encoding="utf-8",
            )
        self.rebuild_index()

    def _page_files(self) -> list[Path]:
        if not self.page_root.exists():
            return []
        return sorted(path for path in self.page_root.rglob("*.md") if path.is_file())

    def _metadata_pages(self) -> list[tuple[Path, dict[str, object], str]]:
        pages = []
        for path in self._page_files():
            metadata, body = parse_frontmatter(path.read_text(encoding="utf-8"))
            if metadata:
                pages.append((path, metadata, body))
        return pages

    def rebuild_index(self) -> None:
        """Build the content-oriented catalog from page frontmatter."""

        self.root.mkdir(parents=True, exist_ok=True)
        self.index_path.write_text(self._render_index(), encoding="utf-8")

    def add_source(self, source: Path, *, title: str | None = None) -> tuple[Path, Path]:
        """Copy one source exactly once and create a page awaiting synthesis."""

        source = source.expanduser().resolve()
        if not source.is_file():
            raise WikiError(f"source is not a file: {source}")
        self.init()

        source_title = title or source.stem.replace("_", " ").replace("-", " ").title()
        slug = slugify(source_title)
        destination = self.root / "raw" / f"{slug}{source.suffix.lower()}"
        page_path = self.page_root / "sources" / f"{slug}.md"
        if destination.exists():
            raise WikiError(f"raw source already exists; refusing to overwrite: {destination}")
        if page_path.exists():
            raise WikiError(f"source page already exists; refusing to overwrite: {page_path}")

        shutil.copy2(source, destination)
        today = date.today().isoformat()
        metadata: dict[str, object] = {
            "type": "source",
            "title": source_title,
            "created": today,
            "updated": today,
            "sources": [f"../../raw/{destination.name}"],
            "summary": "Pending LLM synthesis.",
        }
        page_path.parent.mkdir(parents=True, exist_ok=True)
        page_path.write_text(
            render_frontmatter(metadata)
            + f"# {source_title}\n\n"
            + "## Key claims\n\n- Pending synthesis.\n\n"
            + "## Entities and concepts\n\n- Pending cross-references.\n\n"
            + "## Tensions or open questions\n\n- None recorded yet.\n",
            encoding="utf-8",
        )
        self.rebuild_index()
        relative_source = destination.relative_to(self.root).as_posix()
        self.record(
            "ingest",
            title=source_title,
            details=f"Registered immutable source `{relative_source}`.",
        )
        return destination, page_path

    def record(self, operation: str, *, title: str | None = None, details: str = "") -> None:
        if operation not in {"ingest", "query", "lint"}:
            raise WikiError("operation must be ingest, query, or lint")
        self.log_path.parent.mkdir(parents=True, exist_ok=True)
        if not self.log_path.exists():
            self.log_path.write_text("# Wiki log\n\n", encoding="utf-8")
        label = f" | {title}" if title else ""
        entry = f"## [{date.today().isoformat()}] {operation}{label}\n\n"
        if details:
            entry += f"{details.rstrip()}\n\n"
        with self.log_path.open("a", encoding="utf-8") as log:
            log.write(entry)

    def search(self, query: str, *, include_raw: bool = False) -> list[SearchResult]:
        terms = [term.lower() for term in re.findall(r"[\w-]+", query) if term.strip()]
        if not terms:
            raise WikiError("search query must contain at least one word")
        roots = [self.page_root]
        if include_raw:
            roots.append(self.root / "raw")

        results: list[SearchResult] = []
        phrase = query.strip().lower()
        for root in roots:
            if not root.exists():
                continue
            for path in sorted(root.rglob("*.md")):
                text = path.read_text(encoding="utf-8", errors="replace")
                lower = text.lower()
                score = sum(lower.count(term) for term in terms)
                if phrase and phrase in lower:
                    score += 5
                if score == 0:
                    continue
                lines = text.splitlines()
                line = next(
                    (line.strip() for line in lines if all(term in line.lower() for term in terms)),
                    next(
                        (
                            line.strip()
                            for line in lines
                            if any(term in line.lower() for term in terms)
                        ),
                        "",
                    ),
                )
                results.append(
                    SearchResult(
                        path=path,
                        score=score,
                        snippet=line[:240],
                    )
                )
        return sorted(results, key=lambda result: (-result.score, result.path.as_posix()))

    @staticmethod
    def _link_target(path: Path, target: str) -> Path | None:
        target = target.strip().split("#", 1)[0].split("?", 1)[0]
        if not target or target.startswith(("http://", "https://", "mailto:", "#")):
            return None
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        return (path.parent / target).resolve()

    def lint(self) -> list[str]:
        """Return the wiki health errors. An empty list means healthy."""

        errors: list[str] = []
        for required in (self.index_path, self.log_path, self.root / "raw", self.page_root):
            if not required.exists():
                errors.append(f"missing required wiki path: {required.relative_to(self.root)}")
        if errors:
            return errors

        pages: list[tuple[Path, dict[str, object], str]] = []
        for path in self._page_files():
            try:
                metadata, body = parse_frontmatter(path.read_text(encoding="utf-8"))
            except (OSError, WikiError) as exc:
                errors.append(f"{path.relative_to(self.root)}: {exc}")
                continue
            if not metadata:
                errors.append(f"{path.relative_to(self.root)}: missing frontmatter")
                continue
            pages.append((path, metadata, body))
            missing = [key for key in REQUIRED_METADATA if key not in metadata]
            if missing:
                errors.append(
                    f"{path.relative_to(self.root)}: missing metadata: {', '.join(missing)}"
                )
            for field in ("created", "updated"):
                if field in metadata and not DATE_PATTERN.fullmatch(str(metadata[field])):
                    errors.append(f"{path.relative_to(self.root)}: {field} must be YYYY-MM-DD")
            sources = metadata.get("sources")
            if isinstance(sources, str):
                sources = [sources]
            if not isinstance(sources, list) or not sources:
                errors.append(f"{path.relative_to(self.root)}: sources must be a non-empty list")
            else:
                for source in sources:
                    if not isinstance(source, str):
                        errors.append(
                            f"{path.relative_to(self.root)}: source reference must be a string"
                        )
                        continue
                    target = self._link_target(path, source)
                    if target is not None and not target.exists():
                        errors.append(
                            f"{path.relative_to(self.root)}: missing source reference {source}"
                        )

            for target_text in LINK_PATTERN.findall(body):
                target = self._link_target(path, target_text)
                if target is not None and not target.exists():
                    errors.append(f"{path.relative_to(self.root)}: broken link {target_text}")

        expected_index = self._render_index()
        actual_index = self.index_path.read_text(encoding="utf-8")
        if actual_index != expected_index:
            errors.append("index.md is stale; run `python3 scripts/wiki.py index`")

        inbound: set[Path] = set()
        markdown_files = [
            self.index_path,
            self.log_path,
            *self._page_files(),
            *(self.root / "raw").rglob("*.md"),
        ]
        for markdown in markdown_files:
            if not markdown.is_file():
                continue
            text = markdown.read_text(encoding="utf-8", errors="replace")
            for target_text in LINK_PATTERN.findall(text):
                target = self._link_target(markdown, target_text)
                if target is not None:
                    inbound.add(target)
        for path, _, _ in pages:
            if path.name == "README.md":
                continue
            if path.resolve() not in inbound:
                errors.append(f"{path.relative_to(self.root)}: orphan page")

        return errors

    def _render_index(self) -> str:
        grouped: dict[str, list[tuple[Path, dict[str, object], str]]] = {}
        for page in self._metadata_pages():
            page_type = str(page[1].get("type", "other"))
            grouped.setdefault(_display_type(page_type), []).append(page)
        lines = [
            "# Wiki index",
            "",
            INDEX_MARKER,
            "",
            "This is the content map. Read it first, then follow the most relevant links.",
            "",
        ]
        for category in sorted(grouped, key=lambda value: (value != "Overview", value.lower())):
            lines.extend([f"## {category}", ""])
            for path, metadata, body in sorted(
                grouped[category], key=lambda item: str(item[1].get("title", item[0].stem)).lower()
            ):
                relative = path.relative_to(self.root).as_posix()
                title = str(metadata.get("title", path.stem))
                summary = str(metadata.get("summary", _first_paragraph(body)))
                lines.append(f"- [{title}]({relative}) — {summary}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"


def _wiki_from_args(args: argparse.Namespace) -> Wiki:
    return Wiki(Path(args.wiki_root))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--wiki-root",
        default=str(DEFAULT_WIKI_ROOT),
        help="wiki directory (default: %(default)s)",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("init", help="create the wiki directories and base files")
    subparsers.add_parser("index", help="rebuild index.md from page frontmatter")
    subparsers.add_parser("lint", help="check links, frontmatter, index freshness, and orphans")

    add_source = subparsers.add_parser(
        "add-source", help="register an immutable source and scaffold its page"
    )
    add_source.add_argument("source", type=Path)
    add_source.add_argument("--title")

    search = subparsers.add_parser("search", help="search wiki pages")
    search.add_argument("query")
    search.add_argument("--all", action="store_true", help="also search raw sources")

    log = subparsers.add_parser("log", help="append a parseable operation to log.md")
    log.add_argument("operation", choices=("ingest", "query", "lint"))
    log.add_argument("--title")
    log.add_argument("--details", default="")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    wiki = _wiki_from_args(args)
    try:
        if args.command == "init":
            wiki.init()
            print(f"Initialized {wiki.root}")
        elif args.command == "index":
            wiki.init()
            wiki.rebuild_index()
            print(f"Rebuilt {wiki.index_path}")
        elif args.command == "add-source":
            destination, page = wiki.add_source(args.source, title=args.title)
            print(f"Registered {destination} and scaffolded {page}")
        elif args.command == "search":
            results = wiki.search(args.query, include_raw=args.all)
            if not results:
                print("No matches.")
            else:
                for result in results:
                    print(
                        f"{result.score:>3} {result.path.relative_to(wiki.root)} — {result.snippet}"
                    )
            wiki.record(
                "query", title=args.query, details=f"Found {len(results)} matching page(s)."
            )
        elif args.command == "log":
            wiki.record(args.operation, title=args.title, details=args.details)
            print(f"Recorded {args.operation}")
        elif args.command == "lint":
            errors = wiki.lint()
            if errors:
                for error in errors:
                    print(f"ERROR: {error}")
                return 1
            print(f"Wiki healthy: {len(wiki._page_files())} page(s)")
    except WikiError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
